apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  labels:
    app: react-app-deployment
spec:
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels: 
        app: react-app
    spec:
      containers:
      - image: "marbellacovino/react-app:v.$BUILD_NUMBER"
        name: react-app
        imagePullPolicy: Always
        ports:
          - containerPort: 80
      restartPolicy: Always