apiVersion: v1
kind: Service
metadata:
  name: react-np
  labels:
    app: react-app
spec:
  selector:
    app: react-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: https